# -*- coding: utf-8 -*-
"""Knapsack

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1hxC1FHiSJroQ_1ybfXL7oDw_imG9I446
"""

def knapSack(W, wt, val, n):
 
    if n == 0 or W == 0:
        return 0

    if (wt[n-1] > W):
        return knapSack(W, wt, val, n-1)

    else:
        return max(
            val[n-1] + knapSack(
                W-wt[n-1], wt, val, n-1),
            knapSack(W, wt, val, n-1))
        
n = int(input())
val = list(map(int,input().split()))
w = list(map(int,input().split()))
bag = int(input())

print(knapSack(bag,w,val,n))